name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version(s) to test against as a comma-separated string.'
        required: false
        type: string
        default: '3.12'
      requirements:
        description: 'Path to a requirements.txt file to install before running tests. Leave empty (default) to install from pyproject.toml test dependencies.'
        required: false
        type: string
        default: ''
  workflow_call:
    inputs:
      python-version:
        description: 'Python version(s) to test against as a comma-separated string.'
        required: false
        type: string
        default: '3.12'
      requirements:
        description: 'Path to a requirements.txt file to install before running tests. Leave empty (default) to install from pyproject.toml test dependencies.'
        required: false
        type: string
        default: ''

env:
  DEFAULT_PYTHON_VERSION: ${{ inputs.python-version || '3.12' }} # override via python-version input
  REQUIREMENTS: ${{ inputs.requirements || '' }} # override via requirements input

jobs:
  configure:
    name: Normalize Inputs
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.setup.outputs.python-version }}
      requirements: ${{ steps.setup.outputs.requirements }}
    steps:
      - name: Setup
        id: setup
        uses: stairwaytowonderland/python-reusable-workflows/.github/actions/setup-variables@main
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          requirements: ${{ env.REQUIREMENTS }}

  test:
    name: Test
    needs: [configure]
    uses: stairwaytowonderland/python-reusable-workflows/.github/workflows/test.yaml@main
    permissions:
      contents: read
    with:
      python-version: ${{ needs.configure.outputs.python-version }}
      requirements: ${{ needs.configure.outputs.requirements }}
